AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Get BGG game collection

Resources:

  CollectionsTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        - AttributeName: "username"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "username"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      TableName: "game-chooser--collections"
      StreamSpecification:
        StreamViewType: "NEW_IMAGE"

  FetchCollection:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.fetch_collection
      Runtime: python2.7
      CodeUri: build/package.zip
      Role: arn:aws:iam::017978203355:role/game-chooser--lambda-user
      Timeout: 20
      Events:
        FetchCollectionEndpoint:
          Type: Api
          Properties:
            Path: /collection/{username}
            Method: get

  PingFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.ping
      Runtime: python2.7
      CodeUri: build/package.zip
      Role: arn:aws:iam::017978203355:role/game-chooser--lambda-user
      Events:
        FetchCollectionEndpoint:
          Type: Api
          Properties:
            Path: /ping
            Method: get
