AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Get BGG game collection

Resources:

  CollectionsTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: game-chooser--collections
      PrimaryKey:
        Name: username
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  FetchCollection:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.fetch_collection
      Runtime: python2.7
      CodeUri: build/package.zip
      Role: arn:aws:iam::017978203355:role/game-chooser--lambda-user
      Events:
        FetchCollectionEndpoint:
          Type: Api
          Properties:
            Path: /collection
            Method: get

  PingFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.ping
      Runtime: python2.7
      CodeUri: build/package.zip
      Role: arn:aws:iam::017978203355:role/game-chooser--lambda-user
      Events:
        FetchCollectionEndpoint:
          Type: Api
          Properties:
            Path: /ping
            Method: get
