AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Get BGG game collection

Resources:
  FetchCollection:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.handler
      Runtime: python2.7
      CodeUri: build/package.zip
      Role: arn:aws:iam::017978203355:role/game-chooser--lambda-user
      Events:
        FetchCollectionEndpoint:
          Type: Api
          Properties:
            Path: /collection
            Method: get
  PingFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.ping
      Runtime: python2.7
      CodeUri: build/package.zip
      Role: arn:aws:iam::017978203355:role/game-chooser--lambda-user
